### ISSUE TITLE
Can't connect w/ TightVNC 2.8.3 multiple times with password set

### ISSUE THREAD

**Issue by bk138** [bk138/droidVNC-NG#104]
A user reports:
> ... works for me except once a password is entered things quickly go down hill. I may be able to connect once or twice but not after that. Change pwd and again maybe once or twice you can login. No pwd and it works fine but that's not acceptable.

**Comment by HubKen** [comment]
Hi,

I FOUND A WORKAROUND.	

    • The info you see below I hope you’ll find helpful to augment your server app. I also found a workaround which I’ll review for you. The information below the =========== line is the additional info for you. Also if this help you fix things let me know; I’d be interested in knowing if this info was helpful.
    • 
Workaround :

    • Ok weird as it sounds Debian 11 Bullseye Stable version has an older version of TightVnc’s java viewer – version 1.3.10-2 which for practical uses is pretty much useless. However, thought I’d try it on your app and see what happens.  Well activating it from the command line worked. I logged in 8 or 9 times without problems ( the encoding was preset to Raw). Then the for some reason ( which I didn’t try and diagnose) the app would not even start up but would crash. I mean even before a PID was issued. We mean CRASH !
    • 
    • Then I restarted the TightVnc viewer version 2.8.3 ( without rebooting) and it WORKED! Logged in and out 5 or 6 times until it failed then as I thought about the java.io.EOFException error ( it’s below), I said, “Well , lets try and send a blank pwd. Perhaps that will cause the input stream to close properly on the server side.”  I have enclosed some screen shots showing the way I did it on TightVnc version 2.8.3.  And if I did this then it WORKED EVERY TIME.  I shut every thing client and server down and it still works.
    • 
    • I think this gives you a fairly simple way to modify the code to absolutely clear and null out the input stream for the pwd. But of course I could be wrong :)
    • 
    • Screen Shots:
    • DroidVnc_ErrorTightVnc.png  ---  java.io.EOFException
    • droidVnc_TechDataTigerVnc.png --- Technical specs on the Android phone
    • TightVnc_BlankPwd.png  –- Window presented for pwd ( used twice 1st time blank; 2nd time pwd
    • TightVnc_TryNewConnection.png – shows the error window after submitting a blank pwd
    • 

![droidVnc_TechDataTigerVnc](https://user-images.githubusercontent.com/8150606/193440441-cf4b2b5d-1647-4ed6-8fbe-ec3271e9dc43.png)

![DroidVnc_ErrorTightVnc](https://user-images.githubusercontent.com/8150606/193440471-b7b015a4-9171-4e09-b972-dbc95b613e58.png)

![TightVnc_BlankPwd](https://user-images.githubusercontent.com/8150606/193440487-4f106794-9ec0-49f9-ab75-0f47735489c7.png)

![TightVnc_TryNewConnection](https://user-images.githubusercontent.com/8150606/193440496-ea498c06-f152-4246-8f58-535866bae572.png)

=================================================
The following information is as you requested. I have done some additional testing and it seems the issue is showing up only when the TightVncViewer 2. 8.3 is being used. 

DroidVnc-Ng works as expected with Remmina and TigerVnc so again it appears to be the interaction with TightVNC Viewer version 2.8.3.  I like the TightVnc viewer because of it’s ability to work well with multiple monitors and ability to scale the desktop easily plus easy security with ssh tunneling. The other viewers on Linux are inconvenient because of how they handle multiple monitors and scaling. 

Hopefully we can work together to help solve this issue.

I also tried this same scenario on a T-Mobile Galaxy Note 20 Ultra. The only difference is it took 3 times logging in until it failed to re-login. I have included below the TightVncviewer commandline notations for both a successful login and a failed one.

Another note of interest:
	Once the pwd login fails, (e.g.) on the Note 20 Ultra using say pwd: abc and going to the DroidVnc-Ng on the Note 5 and using the same pwd: abc (or whatever) it also will fail until you change the pwd or use No Pwd at all.

My Suspicion:
The Vnc server when shutting down a session is not completely clearing and making sure the next time and authentication request is coming in that is starts over completely from the very beginning. I suspect this is an issue in the way java is handling things in the background and that other Vnc viewers are aware of it and some how either present it so it’s more easily handled or  

Here is some more info that may help:

Client OS :

Linux xxxxxx 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"

Vnc Client app:
	TightVNC Viewer version 2.8.3

Router :

	For this app I am using an internal lan ip with Port 10204 

OpenWrt 19.07.2 r10947-65030d81f3 

Cell phone:
	T-Mobile Galaxy Note 5 –  SMN920T
	Android 7.0
	Kernel 3.10.61-12322662

	
java -jar tightvnc-jviewer.jar 
Oct 01, 2022 10:23:38 PM com.glavsoft.viewer.Viewer <init>
INFO: TightVNC Viewer version 2.8.3
Oct 01, 2022 10:23:45 PM com.glavsoft.viewer.swing.SwingNetworkConnectionWorker doInBackground
INFO: Trying to connect to 10.26.6.150:10203
Oct 01, 2022 10:23:45 PM com.glavsoft.viewer.swing.SwingNetworkConnectionWorker doInBackground

Successful Login:

java -jar tightvnc-jviewer.jar 
Oct 01, 2022 10:42:20 PM com.glavsoft.viewer.Viewer <init>
INFO: TightVNC Viewer version 2.8.3
Oct 01, 2022 10:42:22 PM com.glavsoft.viewer.swing.SwingNetworkConnectionWorker doInBackground
INFO: Trying to connect to xx.xx.xx.xx:10204
Oct 01, 2022 10:42:22 PM com.glavsoft.viewer.swing.SwingNetworkConnectionWorker doInBackground
INFO: Connecting to host xx.xx.xx.xx:10204
Oct 01, 2022 10:42:22 PM com.glavsoft.viewer.swing.ConnectionPresenter successfulNetworkConnection
INFO: Connected
Oct 01, 2022 10:42:22 PM com.glavsoft.viewer.swing.SwingRfbConnectionWorker doInBackground
INFO: Handshaking with remote host
Oct 01, 2022 10:42:22 PM com.glavsoft.rfb.protocol.handlers.Handshaker matchProtocolVersion
INFO: Server protocol string: RFB 003.008
Oct 01, 2022 10:42:22 PM com.glavsoft.rfb.protocol.handlers.Handshaker handshake
INFO: Set protocol version to: 3.8
Oct 01, 2022 10:42:22 PM com.glavsoft.rfb.protocol.handlers.Handshaker auth37_38
INFO: Security Types received (2): [2, 16]
Oct 01, 2022 10:42:22 PM com.glavsoft.rfb.protocol.handlers.Handshaker selectAuthHandlerId
INFO: Security Type accepted: TIGHT_AUTHENTICATION
Oct 01, 2022 10:42:32 PM com.glavsoft.rfb.protocol.ReceiverTask run
SEVERE: Close session: Cannot read byte
Oct 01, 2022 10:42:32 PM com.glavsoft.viewer.Viewer closeApp
INFO: Connection cancelled.



Failed Login:

INFO: Connecting to host 10.26.6.150:10203
Oct 01, 2022 10:23:45 PM com.glavsoft.viewer.swing.ConnectionPresenter successfulNetworkConnection
INFO: Connected
Oct 01, 2022 10:23:45 PM com.glavsoft.viewer.swing.SwingRfbConnectionWorker doInBackground
INFO: Handshaking with remote host
Oct 01, 2022 10:23:45 PM com.glavsoft.rfb.protocol.handlers.Handshaker matchProtocolVersion
INFO: Server protocol string: RFB 003.008
Oct 01, 2022 10:23:45 PM com.glavsoft.rfb.protocol.handlers.Handshaker handshake
INFO: Set protocol version to: 3.8
Oct 01, 2022 10:23:45 PM com.glavsoft.rfb.protocol.handlers.Handshaker auth37_38
INFO: Security Types received (2): [2, 16]
Oct 01, 2022 10:23:45 PM com.glavsoft.rfb.protocol.handlers.Handshaker selectAuthHandlerId
INFO: Security Type accepted: TIGHT_AUTHENTICATION
Oct 01, 2022 10:23:54 PM com.glavsoft.viewer.swing.SwingRfbConnectionWorker done
SEVERE: Connection Error : java.io.EOFException, possible reason: remote host not responding.
Oct 01, 2022 10:23:59 PM com.glavsoft.viewer.Viewer closeApp
INFO: Connection cancelled.

Hope this helps,

Ken Sproule
[ken@thinkken.com](mailto:ken@thinkken.com)

**Comment by bk138** [comment]
Tried the following which is as close as possible to your setup @HubKen, but it works :shrug: 
* downloaded https://www.tightvnc.com/download/2.8.3/tvnjviewer-2.8.3-bin-gnugpl.zip
* started with `java -jar tightvnc-jviewer.jar` using 
```
java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, mixed mode, sharing)
```
* Connecting to droidVNC-NG v1.3.4 with very simple password set (4 chars)
* works...

With droidVNC-NG v.1.3.3 I'm running into #101, so I assume you are/were using v.1.3.4.

What else could be different with your setup?

**Comment by bk138** [comment]
Tentatively closing, feel free to post something if there's new info.
