### ISSUE TITLE
app can't get input permissions on android 13

### ISSUE THREAD

**Issue by happy-cookie** [bk138/droidVNC-NG#135]
**Can't get input permissions with Android 13 Accessibility Settings.**
After install app send me to 
android Settings->Accessability->More  for set input permissions
But checkbox droidVNC-NG on this page is grayed and user can't change it.

Without input permissions app can't read mouse actions and works in view-only mode.

**Temporary solution**
Solve problem with ADB shell:
```
adb shell cmd appops set net.christianbeier.droidvnc_ng ACCESS_RESTRICTED_SETTINGS  allow
```

**Expected behaviour**
app works after install without any tricky ADB-actions

**Env**
 - droidVNC-NG version: versionName=1.3.5
 - Android version: 13

**Notes**
I'm not sure about correct tagging (bug/feature) of this issue
Maybe you should just add this ADB shell command to readme

**Comment by bk138** [comment]
Thanks for reporting. The checkbox definitely works in Android 12, maybe there were some changes in Android 13?

**Comment by Starbase12** [comment]
Morning together. Yes. It's because Android changed something. Only Apps installed from Play Store and "other" 3rd party app stores are allowed to enable that feature. Apps simply downloaded from an website are not allowed anymore to gain that permission. Unfortunatly Android isn't recognizing that my version of droidVNC-NG was downloaded from F-Droid Store. It should be possible to enable Accessability right but it isn't. 

Maybe some "programming" is required to solve that missbehavior.

(German news board): https://m.winfuture.de/news/129489

**Comment by bk138** [comment]
@happy-cookie did you install from a store or sideload the app?

**Comment by bk138** [comment]
I cannot repro this with a Samsgung Galaxy S20 running Android 13. The a11y checkbox is active when:

* installed via Google Play
* installed from F-Droid
* sideload-installed via Firefox download

**Comment by bk138** [comment]
Do you guys have some news about this?

**Comment by Starbase12** [comment]
Hello bk138,

Sorry for my late answer. Because I wasn't satisfied with the google Pixel I went back to samsung s20. Now I'm using a customized stock Rom and can't reproduce the issue anymore.

I think that this issue has something to do with the ROM you're using. AOSP-Roms like Lineage or (at least) Graphene seem to be affected.

**Comment by bk138** [comment]
Alright, thanks for the info!

**Comment by acoul** [comment]
Greetings, 

I have the exact same issue on a Xiaomi Poco M5s with MIUI 14. 

Using F-Droid to install droidVNC-NG-2.1.6, I get a permissions prompt only for the accessibility. 

No input permissions prompt which remains as denied in red color and there is no way to be able to change this. 

keyboard and mouse do not function. 

alpha vnc lite works fine installed through [APKPure](https://m.apkpure.com/alpha-vnc-lite/de.abr.android.avnc)

**Comment by acoul** [comment]
I followed the following guide about the [permission to access the screen](https://github.com/bk138/droidVNC-NG/blob/master/README.md#notes)

the command:
`adb shell cmd appops set net.christianbeier.droidvnc_ng PROJECT_MEDIA allow`
is succesfull, but there is no change on the input denied issue with the non functional keyboard and mouse

the second command"
`adb shell settings put secure enabled_accessibility_services net.christianbeier.droidvnc_ng/.InputService:$(adb shell settings get secure enabled_accessibility_services)`

returns the following error:
`java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2331)
	at com.android.providers.settings.SettingsProvider.mutateSecureSetting(SettingsProvider.java:1768)
	at com.android.providers.settings.SettingsProvider.insertSecureSetting(SettingsProvider.java:1719)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:467)
	at android.content.ContentProvider.call(ContentProvider.java:2533)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:530)
	at com.android.providers.settings.SettingsService$MyShellCommand.putForUser(SettingsService.java:382)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:278)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
	at android.os.Binder.shellCommand(Binder.java:1054)
	at android.os.Binder.onTransact(Binder.java:882)
	at android.os.Binder.execTransactInternal(Binder.java:1290)
	at android.os.Binder.execTransact(Binder.java:1249)`

issuing just the last part of that command:
`adb shell settings get secure enabled_accessibility_services`

the output is:
`de.abr.android.avnc/de.abr.android.scclib.etc.AcService`

**Note**: I am using this device exclusively as a wifi only device. no SIM card installed. I have turned on USB debugging but I am unable to set USB debugging (security settings) due to lack of a SIM card

**Comment by bk138** [comment]
@acoul accessibility == input. Normally the UI flow should direct you to settings where you can enable the droidvnc-ng service, `adb shell settings get secure enabled_accessibility_services` should then list it. Maybe you can find out what alphaVNC does differently? Maybe more permissions?

**Comment by acoul** [comment]
@bk138 going to Settings --> Additional settings --> Accessibility --> Downloaded apps

and syncing droidVNC-NG options to that of alpha vnc lite and restarting the droidVNC-NG fixed the issue. Thank you for the prompt feedback

![droidVNC-NG_fix_input](https://github.com/bk138/droidVNC-NG/assets/778451/ff110817-6154-4a7a-9c12-fc1f5a0112b3)

**Comment by bk138** [comment]
@acoul nice! where did the  permissions prompt  for  accessibility take you initially? same place or another?

**Comment by acoul** [comment]
> @acoul nice! where did the permissions prompt for accessibility take you initially? same place or another?

it was on a different place. 

in order to grant the accessibility (input) permissions, I had to first start droidVNC-NG, which prompts for the accessibility permissions, though no matter what options I choose on that menu/place, had no success for the input.

without terminating the droidVNC-NG application, going to Settings --> Additional settings --> Accessibility --> Downloaded apps and (disable if it is enabled and then again), enabling the use droidVNC-NG

After that, starting the service (while the application was/is already running) finally granted the input permissions in my case

**Comment by bk138** [comment]
Thats interesting. Would you be able to make a screencast or series of screenshots for each ux flow?

Are you on a custom rom?

What was the droidvnc-ng install method?

Thanks!

**Comment by acoul** [comment]
> Would you be able to make a screencast or series of screenshots for each ux flow?

not an easy task for me currently, but if there are specific questions or tests that you want me to try, sure.

I tried though, to layout above, the exact steps that I managed to get input permissions for droidVNC-NG working on my Xiaomi device

> Are you on a custom rom?

No. I am on a MIUI 14. 

bootloader is locked and some USB debug features still non available as I have no SIM card on this device, just wifi and MIUI is NOT very happy (& cooperative) about this

> What was the droidvnc-ng install method?

at first, F-Droid and then  [APKPure](https://apkpure.com/droidvnc-ng/net.christianbeier.droidvnc_ng). I didn't notice any difference on the two above install methods

I am trying to stay away from anything google on my new android wifi device (a mission impossible)

**Comment by bk138** [comment]
@acoul maybe some background: when the service starts and the frontend UI has "view only" disabled, it pops up a dialog which on click takes the user to a11y (accessibility) settings where they can enable the service for a11y aka input.  I wonder if
- this logic takes you to the wrong place on your device
- or it's the right place but you have to check all the checkboxes
?

**Comment by acoul** [comment]
> @acoul maybe some background: when the service starts and the frontend UI has "view only" disabled, it pops up a dialog which on click takes the user to a11y (accessibility) settings where they can enable the service for a11y aka input. 

@bk138  first, I would like to thank you for your time & patience

> I wonder if
> 
>     * this logic takes you to the wrong place on your device
> 
>     * or it's the right place but you have to check all the checkboxes

it's the second as I am very new to this.  

> Would you be able to make a screencast or series of screenshots for each ux flow?

here is what you asked:

![droidVNC-NG_1](https://github.com/bk138/droidVNC-NG/assets/778451/5d9ba5e1-b0d8-4581-9fde-6971c236b127)
![droidVNC-NG_2](https://github.com/bk138/droidVNC-NG/assets/778451/df3fd95a-f405-462d-8489-7daaec42318c)
![droidVNC-NG_3](https://github.com/bk138/droidVNC-NG/assets/778451/76be5077-7744-43ce-b640-6d5515f3e6fb)
![droidVNC-NG_4](https://github.com/bk138/droidVNC-NG/assets/778451/45f2d8e4-bb0f-47e9-a282-6ede1868ddc7)
![droidVNC-NG_5](https://github.com/bk138/droidVNC-NG/assets/778451/8ae68d23-29db-4bbe-b347-ffe9947884fa)
![droidVNC-NG_6](https://github.com/bk138/droidVNC-NG/assets/778451/d2559467-c253-4fec-9ab1-d43cfd3cf098)
![droidVNC-NG_7](https://github.com/bk138/droidVNC-NG/assets/778451/1866df4c-0d0d-4e2b-8e11-3e3da2131c96)
![droidVNC-NG_8](https://github.com/bk138/droidVNC-NG/assets/778451/50b65995-3413-4949-9fef-84e73f1e801d)
![droidVNC-NG_9](https://github.com/bk138/droidVNC-NG/assets/778451/6f87dbaa-6f82-4249-8301-0a71ad8f2ca8)
![droidVNC-NG_10](https://github.com/bk138/droidVNC-NG/assets/778451/f80ec101-a2f1-4398-b72e-103c3bd57554)
![droidVNC-NG_11](https://github.com/bk138/droidVNC-NG/assets/778451/ad90e57f-3e96-48ca-a0bb-ffb0600970e2)
![droidVNC-NG_12](https://github.com/bk138/droidVNC-NG/assets/778451/7f3499df-af8c-4e94-a9da-b6c9ff470447)

**Comment by bk138** [comment]
ok thanks!
