### ISSUE TITLE
Add tv support

### ISSUE THREAD

**Issue by simpleuserdontwatch** [bk138/droidVNC-NG#152]
Hello, i have an android tv and i want to control it from my computer using vnc, but when i type droid-vnc into platstore it says its not available, can you add surpport to it?

**Comment by bk138** [comment]
Probably, but how to do this?

**Comment by simpleuserdontwatch** [comment]
> Probably, but how to do this?

i really dont know but publish the same app with the same code, if it asks if is it available for tv then press yes or something

**Comment by bk138** [comment]
Tried, but was rejected. More work to do: https://developer.android.com/training/tv/start/start

**Comment by ohnonook** [comment]
I've arrived here because I'm looking for information on how to get what you want to work. I sideloaded the APK a few days ago onto a Chromecast with Google TV and it runs ok, let's tablets Chromebooks etc connect and view, but not interact with the tv by clicks /taps, it's like view only is turned on except the keyboard shortcuts in the readme work. Right now I'm trying the ADB shell commands for the privileges but they don't seem to be working.

Might I have better luck if I used a username (I'm logging in blank) or the SSH option?

I'd love a proper Android TV version though.

**Comment by paolosezart** [comment]
> Hello, i have an android tv and i want to control it from my computer using vnc, but when i type droid-vnc into platstore it says its not available, can you add surpport to it?

https://f-droid.org/en/packages/net.christianbeier.droidvnc_ng/
